### ISSUE TITLE
Taskbar icon is not removed in Windows 10.

### ISSUE THREAD

**Issue by refactorsaurusrex** [refactorsaurusrex/HeadlessSlacker#2]
Received an email today indicating that the Slack taskbar icon isn't hidden when "Hide Taskbar Icon" is clicked on Windows 10. Will look into it once I upgraded to W10 later today.

**Comment by ericellb** [comment]
Great Nick! Will follow, hopefully its an easy fix!

**Comment by refactorsaurusrex** [comment]
Slack has reverted the system tray behavior back to what it was originally, so I won't be fixing this unless something else comes up. 

https://slack-files.com/T024BE7LD-F04DKJP9R-a61c0f491c

**Comment by rredford6** [comment]
Slack seems to have changed their minds back and again no longer will minimize to the tray.  And this still doesn't work in Windows 10.

**Comment by refactorsaurusrex** [comment]
@rredford6 I'll verify on my Win10 machine later this evening...

**Comment by nbcraft** [comment]
Checked for updates on the windows app -> I'm using latest version.
And I can still click the closing icon to make it go to tray.
(You need to have the option activated in Preferences->Windows App)

**Comment by rredford6** [comment]
By "the option" do you mean "Leave app running in notification area when the window is closed"?  I have that checked.
I don't even see the "Hide Taskbar Icon" entry.  Maybe I'm doing something wrong?
![image](https://cloud.githubusercontent.com/assets/25091457/21918148/2c539dc8-d903-11e6-83e5-66951d040e99.png)
I started the Headless Slack application from the start menu.

**Comment by nbcraft** [comment]
Yes that's the option I meant.
With that on, you can use `Close window` and it will go to tray.
You don't need Headless Slack anymore, only slack.

**Comment by rredford6** [comment]
Even with that option ticked it still stays in my taskbar :/

**Comment by refactorsaurusrex** [comment]
Yeah I'm not sure what's different about your system @rredford6, but on my Windows 10 machine I'm able to hide the app to the tray. I made sure I have the latest version. :\

**Comment by rredford6** [comment]
I monkeyed around with settings and still couldn't get Slack to minimize to the tray so I ended up with [RBTray](http://rbtray.sourceforge.net/)

**Comment by paulsmith998** [comment]
In case anyone is interested as well as setting the 'Leave app running in notification area' setting I also had to change the 'flash window when a notification is received' setting to never
