### ISSUE TITLE
Minimize to tray on startup for Windows 10.

### ISSUE THREAD

**Issue by garretwilson** [refactorsaurusrex/HeadlessSlacker#5]
You indicate that Slack now will minimize to the system tray on Windows 10 when you close the window, and indeed it does.

But I have Slack starting when Windows starts up, and the problem is that Slack doesn't automatically close to the system tray. Instead, it opens a window and places that on the taskbar. Sure, it minimizes that window, but it's still there on the taskbar --- taking focus, and getting in the way whenever I switch windows. _I have to go manually close the Slack window to the task bar it each time I start Windows._

Telegram doesn't do this. Skype doesn't do this. They all nicely start up and minimize to the system tray; I can open them if/when I want to. Apparently the Slack development team doesn't know how to fix this. In fact the Slack team (the people I interacted with when filing the issue) seems to use Macintosh; I'm not sure they even understand the issue.

Is there a way for HeadlessSlacker to simply find the stupid window Slack opens on startup, and call its "close" function so that it automatically closes to the task bar?

(On top of that Slack now has a stupid splash screen --- I need to be reminded that Slack is loading each time I start up. When I'm somewhere without an Internet connection, like on a plane, it just hangs and leave the stupid splash screen open. Why do the developers do this sort of thing? But I suppose this is a separate issue.)

**Comment by refactorsaurusrex** [comment]
Sorry my friend, but HeadlessSlacker can't help with that.
